/**
 * DefaultWeb4TSComponent - Web4 Architecture Layer 2 Implementation
 * Implements Web4 TypeScript component standards enforcement
 */

import { Web4TSComponent, ComponentMetadata, CLIStandardValidation, ComponentScaffoldOptions, ComponentDependency } from '../layer3/Web4TSComponent.js';
import * as fs from 'fs/promises';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export class DefaultWeb4TSComponent implements Web4TSComponent {
  private componentName: string = '';
  private version: string = '';
  private targetDirectory: string = '';
  private dependencies: ComponentDependency[] = [];

  // Web4 Empty Constructor Principle
  constructor() {
    // Empty constructor - configuration via setters
  }

  // Configuration methods
  setComponentName(name: string): void {
    this.componentName = name;
  }

  setVersion(version: string): void {
    this.version = version;
  }

  setTargetDirectory(directory: string): void {
    this.targetDirectory = directory;
  }

  setDependencies(dependencies: ComponentDependency[]): void {
    this.dependencies = dependencies;
  }

  // Standard enforcement methods
  async validateLocationResilientCLI(scriptPath: string): Promise<CLIStandardValidation> {
    try {
      const content = await fs.readFile(scriptPath, 'utf-8');
      
      const validation: CLIStandardValidation = {
        isCompliant: false,
        issues: [],
        hasProjectRootDetection: false,
        hasAutoBuilder: false,
        hasContextPreservation: false,
        hasVersionResolution: false
      };

      // Check for project root detection
      if (content.includes('git rev-parse --show-toplevel') || content.includes('find_project_root')) {
        validation.hasProjectRootDetection = true;
      } else {
        validation.issues.push('Missing project root detection logic');
      }

      // Check for auto-build integration
      if (content.includes('npm run build') && content.includes('CLI_PATH')) {
        validation.hasAutoBuilder = true;
      } else {
        validation.issues.push('Missing auto-build integration');
      }

      // Check for context preservation
      if (content.includes('CURRENT_DIR') && content.includes('cd "$CURRENT_DIR"')) {
        validation.hasContextPreservation = true;
      } else {
        validation.issues.push('Missing execution context preservation');
      }

      // Check for version resolution
      if (content.includes('COMPONENT_VERSION') && content.includes('COMPONENT_DIR')) {
        validation.hasVersionResolution = true;
      } else {
        validation.issues.push('Missing component version resolution');
      }

      validation.isCompliant = validation.issues.length === 0;
      return validation;

    } catch (error) {
      return {
        isCompliant: false,
        issues: [`Error reading script: ${(error as Error).message}`],
        hasProjectRootDetection: false,
        hasAutoBuilder: false,
        hasContextPreservation: false,
        hasVersionResolution: false
      };
    }
  }

  async generateLocationResilientCLI(componentName: string, version: string): Promise<string> {
    const cliTemplate = `#!/bin/bash

# ${componentName} CLI Tool - Location Resilient Version
# Web4 Architecture Standard - Generated by Web4TSComponent
# Works from any directory, finds project root via git

# Function to find project root using git
find_project_root() {
    # Try git first (most reliable)
    local git_root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ -n "$git_root" ] && [ -d "$git_root" ]; then
        # Verify it's Web4Articles project by checking for key files
        if [ -f "$git_root/package.json" ] || [ -f "$git_root/README.md" ]; then
            echo "$git_root"
            return 0
        fi
    fi
    
    # Fallback: walk up looking for .git and package.json
    local current_dir="$PWD"
    while [ "$current_dir" != "/" ]; do
        if [ -d "$current_dir/.git" ] && [ -f "$current_dir/package.json" ]; then
            echo "$current_dir"
            return 0
        fi
        current_dir="$(dirname "$current_dir")"
    done
    
    return 1
}

# Find project root
PROJECT_ROOT=$(find_project_root)
if [ -z "$PROJECT_ROOT" ]; then
    echo "❌ Error: Not in a Web4Articles project directory"
    echo "💡 Please run from within the Web4Articles git repository"
    exit 1
fi

export PROJECT_ROOT

# Detect context for the CLI
CURRENT_DIR="$(pwd)"
CONTEXT_INFO=""

# Check if we're in a component directory
if [[ "$CURRENT_DIR" == *"/components/"*"/"*"/"* ]]; then
    COMPONENT_PATH=$(echo "$CURRENT_DIR" | grep -o '.*/components/[^/]*/[^/]*')
    if [ -n "$COMPONENT_PATH" ]; then
        CONTEXT_INFO="component:$COMPONENT_PATH"
    fi
fi

# Default context if none detected
if [ -z "$CONTEXT_INFO" ]; then
    CONTEXT_INFO="arbitrary:$CURRENT_DIR"
fi

# Find the CLI in the components directory structure
COMPONENT_VERSION="${version}"
COMPONENT_DIR="$PROJECT_ROOT/components/${componentName}/$COMPONENT_VERSION"
CLI_SOURCE_PATH="$COMPONENT_DIR/src/ts/layer5/${componentName}CLI.ts"
CLI_PATH="$COMPONENT_DIR/dist/ts/layer5/${componentName}CLI.js"

# Check if compiled CLI exists, if not try to build
if [ ! -f "$CLI_PATH" ]; then
  if [ ! -f "$CLI_SOURCE_PATH" ]; then
    echo "❌ CLI source not found at: $CLI_SOURCE_PATH"
    echo "📁 Component directory: $COMPONENT_DIR"
    exit 1
  fi
  
  echo "🔨 Building ${componentName} CLI v$COMPONENT_VERSION..."
  cd "$COMPONENT_DIR"
  
  # Install dependencies if needed
  if [ ! -d "node_modules" ]; then
    npm install
  fi
  
  # Build the project
  if ! npm run build; then
    echo "❌ Build failed for ${componentName} v$COMPONENT_VERSION"
    exit 1
  fi
  
  if [ ! -f "$CLI_PATH" ]; then
    echo "❌ CLI still not found at: $CLI_PATH after build"
    exit 1
  fi
fi

# Check for Node.js
if ! command -v node >/dev/null 2>&1; then
    echo "❌ Error: Node.js is required but not installed"
    exit 1
fi

# Execute the CLI with context info and all arguments
cd "$CURRENT_DIR"
DIRECTORY_CONTEXT="$CONTEXT_INFO" node "$CLI_PATH" "$@"
`;

    return cliTemplate;
  }

  async scaffoldComponent(options: ComponentScaffoldOptions): Promise<ComponentMetadata> {
    const componentPath = path.join(this.targetDirectory, 'components', options.componentName, options.version);
    
    try {
      // Create directory structure
      await fs.mkdir(componentPath, { recursive: true });
      await fs.mkdir(path.join(componentPath, 'src/ts/layer2'), { recursive: true });
      await fs.mkdir(path.join(componentPath, 'src/ts/layer3'), { recursive: true });
      await fs.mkdir(path.join(componentPath, 'src/ts/layer5'), { recursive: true });

      if (options.includeSpecFolder) {
        await fs.mkdir(path.join(componentPath, 'spec/requirements'), { recursive: true });
        await fs.mkdir(path.join(componentPath, 'spec/requirements.md'), { recursive: true });
      }

      // Generate package.json
      const packageJson = {
        name: `@web4x/${options.componentName.toLowerCase()}`,
        version: options.version,
        type: "module",
        description: `Web4 ${options.componentName} Component`,
        main: `src/ts/layer5/${options.componentName}CLI.ts`,
        scripts: {
          build: "tsc",
          ...(options.includeVitest ? { test: "vitest" } : {}),
          start: `node -r ts-node/register src/ts/layer5/${options.componentName}CLI.ts`
        },
        devDependencies: {
          "@types/node": "^20.0.0",
          "ts-node": "^10.9.0",
          "typescript": "^5.0.0",
          ...(options.includeVitest ? { vitest: "^1.0.0" } : {})
        }
      };

      await fs.writeFile(
        path.join(componentPath, 'package.json'),
        JSON.stringify(packageJson, null, 2)
      );

      // Generate tsconfig.json
      const tsConfig = {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "node",
          declaration: true,
          declarationMap: true,
          sourceMap: true,
          outDir: "./dist",
          rootDir: "./src",
          removeComments: false,
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true
        },
        include: ["src/**/*"],
        exclude: ["node_modules", "dist"]
      };

      await fs.writeFile(
        path.join(componentPath, 'tsconfig.json'),
        JSON.stringify(tsConfig, null, 2)
      );

      // Generate CLI if requested
      if (options.includeCLI) {
        const cliScript = await this.generateLocationResilientCLI(options.componentName, options.version);
        await fs.writeFile(path.join(componentPath, `${options.componentName.toLowerCase()}.sh`), cliScript);
      }

      // Generate dependency-aware build scripts
      if (options.dependencies && options.dependencies.length > 0) {
        const installDepsScript = await this.generateInstallDepsScript(options.componentName, options.version, options.dependencies);
        await fs.writeFile(path.join(componentPath, 'install-deps.sh'), installDepsScript);
        
        const buildScript = await this.generateBuildScript(options.componentName, options.version, options.dependencies);
        await fs.writeFile(path.join(componentPath, 'build.sh'), buildScript);
        
        // Make scripts executable
        const { spawn } = await import('child_process');
        await new Promise<void>((resolve) => {
          const child = spawn('chmod', ['+x', 'install-deps.sh', 'build.sh'], { cwd: componentPath });
          child.on('close', () => resolve());
        });
      }

      const metadata: ComponentMetadata = {
        name: options.componentName,
        version: options.version,
        type: 'Web4Component',
        hasLocationResilientCLI: options.includeCLI,
        hasEmptyConstructors: true,
        hasScenarioSupport: true,
        hasLayeredArchitecture: options.includeLayerArchitecture,
        dependencies: options.dependencies
      };

      return metadata;

    } catch (error) {
      throw new Error(`Failed to scaffold component: ${(error as Error).message}`);
    }
  }

  async auditComponentCompliance(componentPath: string): Promise<ComponentMetadata> {
    const packageJsonPath = path.join(componentPath, 'package.json');
    const tsConfigPath = path.join(componentPath, 'tsconfig.json');
    
    try {
      const packageContent = await fs.readFile(packageJsonPath, 'utf-8');
      const packageData = JSON.parse(packageContent);

      const metadata: ComponentMetadata = {
        name: packageData.name || 'Unknown',
        version: packageData.version || 'Unknown',
        type: 'Web4Component',
        hasLocationResilientCLI: false,
        hasEmptyConstructors: false,
        hasScenarioSupport: false,
        hasLayeredArchitecture: false
      };

      // Check for layered architecture
      try {
        await fs.access(path.join(componentPath, 'src/ts/layer2'));
        await fs.access(path.join(componentPath, 'src/ts/layer3'));
        await fs.access(path.join(componentPath, 'src/ts/layer5'));
        metadata.hasLayeredArchitecture = true;
      } catch {
        // Layers not found
      }

      // Check for CLI script
      const files = await fs.readdir(componentPath);
      const cliScript = files.find(f => f.endsWith('.sh'));
      if (cliScript) {
        const validation = await this.validateLocationResilientCLI(path.join(componentPath, cliScript));
        metadata.hasLocationResilientCLI = validation.isCompliant;
      }

      return metadata;

    } catch (error) {
      throw new Error(`Failed to audit component: ${(error as Error).message}`);
    }
  }

  async generateComplianceReport(components: string[]): Promise<string> {
    let report = '# Web4 Component Compliance Report\\n\\n';
    
    for (const componentPath of components) {
      try {
        const metadata = await this.auditComponentCompliance(componentPath);
        
        report += `## ${metadata.name} v${metadata.version}\\n`;
        report += `- Location-Resilient CLI: ${metadata.hasLocationResilientCLI ? '✅' : '❌'}\\n`;
        report += `- Layered Architecture: ${metadata.hasLayeredArchitecture ? '✅' : '❌'}\\n`;
        report += `- Empty Constructors: ${metadata.hasEmptyConstructors ? '✅' : '⚠️ (Not verified)'}\\n`;
        report += `- Scenario Support: ${metadata.hasScenarioSupport ? '✅' : '⚠️ (Not verified)'}\\n\\n`;
        
      } catch (error) {
        report += `## ${componentPath}\\n`;
        report += `- Error: ${(error as Error).message}\\n\\n`;
      }
    }
    
    return report;
  }

  getLocationResilientCLIStandard(): string {
    return `# Web4 Location-Resilient CLI Standard

## Overview
All Web4 components must provide CLIs that work from any directory within the project.

## Required Features
1. **Project Root Detection**: Use git rev-parse or directory traversal
2. **Component Version Resolution**: Locate CLI in components/[Name]/[Version] structure  
3. **Auto-Build Integration**: Build component if CLI not compiled
4. **Context Preservation**: Return to original execution directory

## Implementation Pattern
Use Web4TSComponent.generateLocationResilientCLI() to create standard-compliant scripts.

## Validation
Use Web4TSComponent.validateLocationResilientCLI() to check compliance.
`;
  }

  getWeb4ArchitectureGuidelines(): string {
    return `# Web4 Architecture Guidelines

## Core Principles
1. **Empty Constructor Principle**: All classes must have empty constructors
2. **Scenario-First Development**: Objects are hibernatable scenarios
3. **IOR Architecture**: Reference objects by Interoperable Object References
4. **Semantic Invariants**: Location, format, and other implementation details are irrelevant
5. **Layered Architecture**: Layer 2 (Implementation), Layer 3 (Interface), Layer 5 (CLI/UI)

## Component Structure
- src/ts/layer2/: Implementation classes
- src/ts/layer3/: Interface definitions  
- src/ts/layer5/: CLI and UI components
- spec/requirements/: Scenario files
- spec/requirements.md/: Generated documentation

## Standards Compliance
Use Web4TSComponent for scaffolding and validation.
`;
  }

  generateDependenciesBuildSection(dependencies: ComponentDependency[]): string {
    if (!dependencies || dependencies.length === 0) {
      return '# No dependencies to build';
    }

    let section = '# Build component dependencies first\n';
    section += 'echo "🔗 Building component dependencies..."\n\n';

    for (const dep of dependencies) {
      section += `# Build ${dep.component}@${dep.version}\n`;
      section += `DEP_PATH="$PROJECT_ROOT/components/${dep.component}/${dep.version}"\n`;
      section += `if [ ! -d "$DEP_PATH" ]; then\n`;
      section += `    echo "❌ Error: Dependency not found: ${dep.component}@${dep.version} at $DEP_PATH"\n`;
      section += `    exit 1\n`;
      section += `fi\n\n`;
      
      section += `echo "📦 Building dependency: ${dep.component}@${dep.version}"\n`;
      section += `cd "$DEP_PATH"\n\n`;
      
      section += `# Check if already built\n`;
      section += `if [ ! -d "dist" ] || [ "package.json" -nt "dist" ]; then\n`;
      section += `    echo "🔨 Installing and building ${dep.component}@${dep.version}..."\n`;
      section += `    npm install\n`;
      section += `    npm run build\n`;
      section += `    echo "✅ Built ${dep.component}@${dep.version}"\n`;
      section += `else\n`;
      section += `    echo "✅ ${dep.component}@${dep.version} already built"\n`;
      section += `fi\n\n`;
      
      section += `cd "$COMPONENT_DIR"\n\n`;
    }

    return section;
  }

  generateDependenciesVerifySection(dependencies: ComponentDependency[]): string {
    if (!dependencies || dependencies.length === 0) {
      return '# No dependencies to verify';
    }

    let section = '# Verify all dependencies are built\n';
    section += 'echo "🔍 Verifying component dependencies..."\n\n';

    for (const dep of dependencies) {
      section += `# Verify ${dep.component}@${dep.version}\n`;
      section += `DEP_PATH="$PROJECT_ROOT/components/${dep.component}/${dep.version}"\n`;
      section += `if [ ! -d "$DEP_PATH/dist" ]; then\n`;
      section += `    echo "❌ Error: Dependency not built: ${dep.component}@${dep.version}"\n`;
      section += `    echo "💡 Run: cd $DEP_PATH && npm install && npm run build"\n`;
      section += `    exit 1\n`;
      section += `fi\n`;
      section += `echo "✅ Verified ${dep.component}@${dep.version}"\n\n`;
    }

    return section;
  }

  async generateInstallDepsScript(componentName: string, version: string, dependencies: ComponentDependency[]): Promise<string> {
    const templatePath = path.join(__dirname, '../../../templates/sh/install-deps.sh.template');
    
    try {
      const template = await fs.readFile(templatePath, 'utf-8');
      const dependenciesBuildSection = this.generateDependenciesBuildSection(dependencies);
      
      return template
        .replace(/{COMPONENT_NAME}/g, componentName)
        .replace(/{VERSION}/g, version)
        .replace(/{DEPENDENCIES_BUILD_SECTION}/g, dependenciesBuildSection);
    } catch (error) {
      throw new Error(`Failed to generate install-deps.sh: ${(error as Error).message}`);
    }
  }

  async generateBuildScript(componentName: string, version: string, dependencies: ComponentDependency[]): Promise<string> {
    const templatePath = path.join(__dirname, '../../../templates/sh/build.sh.template');
    
    try {
      const template = await fs.readFile(templatePath, 'utf-8');
      const dependenciesVerifySection = this.generateDependenciesVerifySection(dependencies);
      
      return template
        .replace(/{COMPONENT_NAME}/g, componentName)
        .replace(/{VERSION}/g, version)
        .replace(/{DEPENDENCIES_VERIFY_SECTION}/g, dependenciesVerifySection);
    } catch (error) {
      throw new Error(`Failed to generate build.sh: ${(error as Error).message}`);
    }
  }

  async buildDependencies(componentName: string): Promise<void> {
    console.log(`🔗 Building dependencies for ${componentName}...`);
    
    for (const dep of this.dependencies) {
      const depPath = dep.path || path.join(this.targetDirectory || process.cwd(), 'components', dep.component, dep.version);
      
      console.log(`📦 Building dependency: ${dep.component}@${dep.version}`);
      
      try {
        // Check if dependency exists
        await fs.access(depPath);
        
        // Check if already built
        const distPath = path.join(depPath, 'dist');
        let needsBuild = true;
        
        try {
          await fs.access(distPath);
          // Check if package.json is newer than dist
          const packageJsonPath = path.join(depPath, 'package.json');
          const packageStat = await fs.stat(packageJsonPath);
          const distStat = await fs.stat(distPath);
          needsBuild = packageStat.mtime > distStat.mtime;
        } catch {
          // dist doesn't exist, needs build
          needsBuild = true;
        }
        
        if (needsBuild) {
          console.log(`🔨 Building ${dep.component}@${dep.version}...`);
          
          // Install dependencies first
          const installProcess = await import('child_process');
          await new Promise<void>((resolve, reject) => {
            const child = installProcess.spawn('npm', ['install'], {
              cwd: depPath,
              stdio: 'inherit'
            });
            
            child.on('close', (code) => {
              if (code === 0) {
                resolve();
              } else {
                reject(new Error(`npm install failed for ${dep.component}@${dep.version} with code ${code}`));
              }
            });
          });
          
          // Build the component
          await new Promise<void>((resolve, reject) => {
            const child = installProcess.spawn('npm', ['run', 'build'], {
              cwd: depPath,
              stdio: 'inherit'
            });
            
            child.on('close', (code) => {
              if (code === 0) {
                console.log(`✅ Successfully built ${dep.component}@${dep.version}`);
                resolve();
              } else {
                reject(new Error(`npm run build failed for ${dep.component}@${dep.version} with code ${code}`));
              }
            });
          });
        } else {
          console.log(`✅ ${dep.component}@${dep.version} already built`);
        }
        
      } catch (error) {
        console.error(`❌ Failed to build dependency ${dep.component}@${dep.version}:`, (error as Error).message);
        throw error;
      }
    }
    
    console.log(`✅ All dependencies built for ${componentName}`);
  }

  // Scenario support (Web4 Scenario-First Development)
  toScenario(): any {
    return {
      ior: {
        uuid: 'web4tscomponent-' + Date.now(),
        type: 'Web4TSComponent',
        version: '0.1.0.0'
      },
      model: {
        componentName: this.componentName,
        version: this.version,
        targetDirectory: this.targetDirectory,
        dependencies: this.dependencies,
        created: new Date().toISOString(),
        updated: new Date().toISOString()
      }
    };
  }

  fromScenario(scenario: any): void {
    if (scenario.model) {
      this.componentName = scenario.model.componentName || '';
      this.version = scenario.model.version || '';
      this.targetDirectory = scenario.model.targetDirectory || '';
      this.dependencies = scenario.model.dependencies || [];
    }
  }
}



