/**
 * IdealMinimalComponent Basic Tests
 * Auto-generated by Web4TSComponent
 */

import { describe, it, expect } from 'vitest';
import { DefaultIdealMinimalComponent } from '../src/ts/layer2/DefaultIdealMinimalComponent.js';
import { execSync } from 'child_process';
import { existsSync } from 'fs';
import * as path from 'path';

describe('IdealMinimalComponent Basic Tests', () => {
  it('should create instance successfully', () => {
    const component = new DefaultIdealMinimalComponent();
    expect(component).toBeDefined();
  });

  it('should have empty constructor (Web4 standard)', () => {
    const component = new DefaultIdealMinimalComponent();
    expect(component).toBeInstanceOf(DefaultIdealMinimalComponent);
  });
});

describe('IdealMinimalComponent CLI Location Resilience', () => {
  it('should work when called from scripts/ directory', () => {
    // Find project root ONCE by walking up from test file location
    // This MUST match the logic in DefaultWeb4TSComponent.findProjectRootFrom()
    const findProjectRoot = (startDir: string): string => {
      let currentDir = path.resolve(startDir);
      
      // First priority: Look for package.json + components/ directory
      // This is MORE SPECIFIC and will correctly identify test/data or project root
      while (currentDir !== path.dirname(currentDir)) {
        if (existsSync(path.join(currentDir, 'package.json')) &&
            existsSync(path.join(currentDir, 'components'))) {
          return currentDir;
        }
        currentDir = path.dirname(currentDir);
      }
      
      // Fallback: Look for .git (for projects without components/ dir)
      currentDir = path.resolve(startDir);
      while (currentDir !== path.dirname(currentDir)) {
        if (existsSync(path.join(currentDir, '.git'))) {
          return currentDir;
        }
        currentDir = path.dirname(currentDir);
      }
      
      return path.resolve(startDir);
    };
    
    // Discover project root once, then use absolute paths everywhere
    const projectRoot = findProjectRoot(__dirname);
    const scriptsDir = path.join(projectRoot, 'scripts');
    const cliScriptPath = path.join(scriptsDir, 'idealminimalcomponent');
    
    // Verify CLI script symlink exists in scripts/
    expect(existsSync(cliScriptPath)).toBe(true);
    
    // Test: Run CLI from scripts/ directory
    // This verifies location-resilient symlink resolution works correctly
    try {
      const result = execSync('./idealminimalcomponent', {
        cwd: scriptsDir,
        encoding: 'utf-8',
        timeout: 10000
      });
      
      expect(result).toContain('IdealMinimalComponent CLI Tool');
      console.log('   ✅ CLI works from scripts/ directory (location-resilient)');
    } catch (error: any) {
      console.error('   ❌ CLI FAILED from scripts/ directory');
      console.error('   Error:', error.message);
      console.error('\n🔴 BUG: CLI script is NOT location-resilient!');
      console.error('   The CLI script needs proper symlink resolution logic.');
      throw new Error(`CLI script failed from scripts/ directory: ${error.message}`);
    }
  });
});

describe('IdealMinimalComponent Delegated Infrastructure Methods', () => {
  it('should execute info command (delegation to Web4TSComponent)', () => {
    // Find project root
    const findProjectRoot = (startDir: string): string => {
      let currentDir = path.resolve(startDir);
      while (currentDir !== path.dirname(currentDir)) {
        if (existsSync(path.join(currentDir, 'package.json')) &&
            existsSync(path.join(currentDir, 'components'))) {
          return currentDir;
        }
        currentDir = path.dirname(currentDir);
      }
      return path.resolve(startDir);
    };
    
    const projectRoot = findProjectRoot(__dirname);
    const scriptsDir = path.join(projectRoot, 'scripts');
    const cliScriptPath = path.join(scriptsDir, 'idealminimalcomponent');
    
    try {
      const result = execSync('./idealminimalcomponent info', {
        cwd: scriptsDir,
        encoding: 'utf-8',
        timeout: 10000
      });
      
      expect(result).toContain('Component Model Information');
      expect(result).toContain('Component Identity');
      expect(result).toContain('IdealMinimalComponent');
      console.log('   ✅ info() command works (delegated to Web4TSComponent)');
    } catch (error: any) {
      console.error('   ❌ info() command FAILED');
      console.error('   Error:', error.message);
      throw new Error(`info() command failed: ${error.message}`);
    }
  });

  it('should execute links command (delegation to Web4TSComponent)', () => {
    const findProjectRoot = (startDir: string): string => {
      let currentDir = path.resolve(startDir);
      while (currentDir !== path.dirname(currentDir)) {
        if (existsSync(path.join(currentDir, 'package.json')) &&
            existsSync(path.join(currentDir, 'components'))) {
          return currentDir;
        }
        currentDir = path.dirname(currentDir);
      }
      return path.resolve(startDir);
    };
    
    const projectRoot = findProjectRoot(__dirname);
    const scriptsDir = path.join(projectRoot, 'scripts');
    
    try {
      const result = execSync('./idealminimalcomponent links', {
        cwd: scriptsDir,
        encoding: 'utf-8',
        timeout: 10000
      });
      
      expect(result).toContain('Semantic Version Links');
      console.log('   ✅ links() command works (delegated to Web4TSComponent)');
    } catch (error: any) {
      console.error('   ❌ links() command FAILED');
      console.error('   Error:', error.message);
      throw new Error(`links() command failed: ${error.message}`);
    }
  });
});

describe('IdealMinimalComponent Radical OOP: info() with Context Delegation', () => {
  /**
   * @pdca 2025-11-10-UTC-1010.pdca.md - Radical OOP: getTarget() single source of truth
   * 
   * The info() command should show a quick header and delegate to the target component.
   * When IdealMinimalComponent doesn't set specific paths, it should show paths from
   * the Web4TSComponent it delegates to.
   */
  
  const findProjectRoot = (startDir: string): string => {
    let currentDir = path.resolve(startDir);
    while (currentDir !== path.dirname(currentDir)) {
      if (existsSync(path.join(currentDir, 'package.json')) &&
          existsSync(path.join(currentDir, 'components'))) {
        return currentDir;
      }
      currentDir = path.dirname(currentDir);
    }
    return path.resolve(startDir);
  };

  it('should show Component Model Information header', () => {
    const projectRoot = findProjectRoot(__dirname);
    const scriptsDir = path.join(projectRoot, 'scripts');
    
    const result = execSync('./idealminimalcomponent info', {
      cwd: scriptsDir,
      encoding: 'utf-8',
      timeout: 10000
    });
    
    // Must have the header from printQuickHeader()
    expect(result).toContain('📊 Component Model Information');
    expect(result).toContain('================================================================================');
  });

  it('should show component identity', () => {
    const projectRoot = findProjectRoot(__dirname);
    const scriptsDir = path.join(projectRoot, 'scripts');
    
    const result = execSync('./idealminimalcomponent info', {
      cwd: scriptsDir,
      encoding: 'utf-8',
      timeout: 10000
    });
    
    // Component Identity section
    expect(result).toContain('Component Identity:');
    expect(result).toContain('Component:');
    expect(result).toContain('IdealMinimalComponent');
    expect(result).toContain('Version:');
    expect(result).toContain('0.3.18.4');
  });

  it('should show context delegation info', () => {
    const projectRoot = findProjectRoot(__dirname);
    const scriptsDir = path.join(projectRoot, 'scripts');
    
    const result = execSync('./idealminimalcomponent info', {
      cwd: scriptsDir,
      encoding: 'utf-8',
      timeout: 10000
    });
    
    // Context Delegation section should exist
    expect(result).toContain('Context Delegation:');
    expect(result).toContain('Caller Component:');
    expect(result).toContain('Target Component:');
  });

  it('should work when called via symlink after sourcing source.env', () => {
    // This is the EXACT user workflow that was broken with pwd (not pwd -P)
    const projectRoot = findProjectRoot(__dirname);
    const sourceEnvPath = path.join(projectRoot, 'source.env');
    
    if (!existsSync(sourceEnvPath)) {
      console.log('   ⚠️  Skipping source.env test (file not found)');
      return;
    }
    
    const command = `. "${sourceEnvPath}" 2>/dev/null && idealminimalcomponent info`;
    
    try {
      const result = execSync(command, {
        cwd: projectRoot,
        encoding: 'utf-8',
        shell: '/bin/bash',
        timeout: 15000
      });
      
      // Critical: Must produce output (not silent like before pwd -P fix)
      expect(result.trim().length).toBeGreaterThan(0);
      expect(result).toContain('Component Model Information');
      expect(result).toContain('IdealMinimalComponent');
      console.log('   ✅ Symlink workflow works (. source.env && idealminimalcomponent info)');
    } catch (error: any) {
      console.error('   ❌ Symlink workflow FAILED');
      console.error('   Error:', error.message);
      throw new Error(`Symlink workflow failed: ${error.message}`);
    }
  });

  it('should have pwd -P in wrapper (symlink resolution fix)', () => {
    const projectRoot = findProjectRoot(__dirname);
    const componentDir = path.join(projectRoot, 'components/IdealMinimalComponent/0.3.18.4');
    const wrapperPath = path.join(componentDir, 'idealminimalcomponent');
    
    expect(existsSync(wrapperPath)).toBe(true);
    
    const wrapperContent = execSync(`cat "${wrapperPath}"`, { encoding: 'utf-8' });
    
    // Critical: Wrapper must use pwd -P (not just pwd) for symlink resolution
    expect(wrapperContent).toContain('pwd -P');
    expect(wrapperContent).toMatch(/SCRIPT_DIR=.*pwd -P/);
    console.log('   ✅ Wrapper uses pwd -P (template fix inherited)');
  });
});

