#!/bin/bash

# Tootsie CLI Script - Location-Resilient Web4 Quality Consciousness
# Radical Object-Oriented Testing Framework
# Auto-generated by Web4TSComponent scaffolder

# Location-resilient project root detection
detect_project_root() {
    local current_dir="$(pwd)"
    
    # Search up the directory tree for Web4 project markers
    while [[ "$current_dir" != "/" ]]; do
        if [[ -f "$current_dir/package.json" ]] && [[ -d "$current_dir/components" ]]; then
            echo "$current_dir"
            return 0
        fi
        current_dir="$(dirname "$current_dir")"
    done
    
    echo "Error: Web4 project root not found" >&2
    return 1
}

# Get project root
PROJECT_ROOT=$(detect_project_root)
if [[ $? -ne 0 ]]; then
    exit 1
fi

# Component detection
COMPONENT_DIR="$PROJECT_ROOT/components/Tootsie/0.1.0.0"

if [[ ! -d "$COMPONENT_DIR" ]]; then
    echo "Error: Tootsie component not found at $COMPONENT_DIR" >&2
    exit 1
fi

# Change to component directory
cd "$COMPONENT_DIR"

# Show Tootsie banner if no arguments
if [[ $# -eq 0 ]]; then
    echo "🎭 Tootsie - Web4 Quality Consciousness"
    echo "   Radical Object-Oriented Testing Framework"
    echo "   Version: 0.1.0.0"
    echo ""
    echo "Usage: tootsie <command> [options]"
    echo "Try: tootsie help"
    exit 0
fi

# Check if built version exists, otherwise use dev mode
if [[ -f "dist/layer5/TootsieCLI.js" ]]; then
    # Use compiled version
    exec node dist/layer5/TootsieCLI.js "$@"
else
    # Use development version with ts-node
    exec npx ts-node src/ts/layer5/TootsieCLI.ts "$@"
fi