/**
 * RemoteController Basic Tests
 * Auto-generated by Web4TSComponent
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { DefaultRemoteController } from '../src/ts/layer2/DefaultRemoteController.js';
import { execSync, exec } from 'child_process';
import { existsSync } from 'fs';
import * as path from 'path';
import { promisify } from 'util';

const execAsync = promisify(exec);

describe('RemoteController Basic Tests', () => {
  it('should create instance successfully', () => {
    const component = new DefaultRemoteController();
    expect(component).toBeDefined();
  });

  it('should have empty constructor (Web4 standard)', () => {
    const component = new DefaultRemoteController();
    expect(component).toBeInstanceOf(DefaultRemoteController);
  });
});

describe('RemoteController CLI Location Resilience', () => {
  it('should work when called from scripts/ directory', () => {
    // Find project root ONCE by walking up from test file location
    // This MUST match the logic in DefaultWeb4TSComponent.findProjectRootFrom()
    const findProjectRoot = (startDir: string): string => {
      let currentDir = path.resolve(startDir);
      
      // First priority: Look for package.json + components/ directory
      // This is MORE SPECIFIC and will correctly identify test/data or project root
      while (currentDir !== path.dirname(currentDir)) {
        if (existsSync(path.join(currentDir, 'package.json')) &&
            existsSync(path.join(currentDir, 'components'))) {
          return currentDir;
        }
        currentDir = path.dirname(currentDir);
      }
      
      // Fallback: Look for .git (for projects without components/ dir)
      currentDir = path.resolve(startDir);
      while (currentDir !== path.dirname(currentDir)) {
        if (existsSync(path.join(currentDir, '.git'))) {
          return currentDir;
        }
        currentDir = path.dirname(currentDir);
      }
      
      return path.resolve(startDir);
    };
    
    // Discover project root once, then use absolute paths everywhere
    const projectRoot = findProjectRoot(__dirname);
    const scriptsDir = path.join(projectRoot, 'scripts');
    const cliScriptPath = path.join(scriptsDir, 'remotecontroller');
    
    // Verify CLI script symlink exists in scripts/
    expect(existsSync(cliScriptPath)).toBe(true);
    
    // Test: Run CLI from scripts/ directory
    // This verifies location-resilient symlink resolution works correctly
    try {
      const result = execSync('./remotecontroller', {
        cwd: scriptsDir,
        encoding: 'utf-8',
        timeout: 10000
      });
      
      expect(result).toContain('RemoteController CLI Tool');
      console.log('   ✅ CLI works from scripts/ directory (location-resilient)');
    } catch (error: any) {
      console.error('   ❌ CLI FAILED from scripts/ directory');
      console.error('   Error:', error.message);
      console.error('\n🔴 BUG: CLI script is NOT location-resilient!');
      console.error('   The CLI script needs proper symlink resolution logic.');
      throw new Error(`CLI script failed from scripts/ directory: ${error.message}`);
    }
  });
});

describe('RemoteController Delegated Infrastructure Methods', () => {
  it('should execute info command (delegation to Web4TSComponent)', () => {
    // Find project root
    const findProjectRoot = (startDir: string): string => {
      let currentDir = path.resolve(startDir);
      while (currentDir !== path.dirname(currentDir)) {
        if (existsSync(path.join(currentDir, 'package.json')) &&
            existsSync(path.join(currentDir, 'components'))) {
          return currentDir;
        }
        currentDir = path.dirname(currentDir);
      }
      return path.resolve(startDir);
    };
    
    const projectRoot = findProjectRoot(__dirname);
    const scriptsDir = path.join(projectRoot, 'scripts');
    const cliScriptPath = path.join(scriptsDir, 'remotecontroller');
    
    try {
      const result = execSync('./remotecontroller info', {
        cwd: scriptsDir,
        encoding: 'utf-8',
        timeout: 10000
      });
      
      expect(result).toContain('Component Model Information');
      expect(result).toContain('Component Identity');
      expect(result).toContain('RemoteController');
      console.log('   ✅ info() command works (delegated to Web4TSComponent)');
    } catch (error: any) {
      console.error('   ❌ info() command FAILED');
      console.error('   Error:', error.message);
      throw new Error(`info() command failed: ${error.message}`);
    }
  });

  it('should execute links command (delegation to Web4TSComponent)', () => {
    const findProjectRoot = (startDir: string): string => {
      let currentDir = path.resolve(startDir);
      while (currentDir !== path.dirname(currentDir)) {
        if (existsSync(path.join(currentDir, 'package.json')) &&
            existsSync(path.join(currentDir, 'components'))) {
          return currentDir;
        }
        currentDir = path.dirname(currentDir);
      }
      return path.resolve(startDir);
    };
    
    const projectRoot = findProjectRoot(__dirname);
    const scriptsDir = path.join(projectRoot, 'scripts');
    
    try {
      const result = execSync('./remotecontroller links', {
        cwd: scriptsDir,
        encoding: 'utf-8',
        timeout: 10000
      });
      
      expect(result).toContain('Semantic Version Links');
      console.log('   ✅ links() command works (delegated to Web4TSComponent)');
    } catch (error: any) {
      console.error('   ❌ links() command FAILED');
      console.error('   Error:', error.message);
      throw new Error(`links() command failed: ${error.message}`);
    }
  });
});

/**
 * Helper function to get Cursor PIDs on current platform
 */
async function getCursorPids(): Promise<Set<number>> {
  const pids = new Set<number>();
  
  if (process.platform === 'darwin') {
    try {
      const { stdout } = await execAsync(`ps aux | grep -i "Cursor.app/Contents/MacOS/Cursor" | grep -v "Helper" | grep -v grep | awk '{print $2}'`);
      const pidLines = stdout.trim().split('\n').filter(line => line.trim());
      pidLines.forEach(line => {
        const pid = parseInt(line.trim(), 10);
        if (!isNaN(pid) && pid > 0) {
          pids.add(pid);
        }
      });
    } catch {
      // No processes found or error - that's okay
    }
  } else if (process.platform === 'win32') {
    try {
      const { stdout } = await execAsync(`tasklist /FI "IMAGENAME eq Cursor.exe" /FO CSV | findstr Cursor.exe`);
      const lines = stdout.trim().split('\n').filter(line => line.trim());
      lines.forEach(line => {
        const match = line.match(/"([^"]+)","([^"]+)"/);
        if (match && match[2]) {
          const pid = parseInt(match[2], 10);
          if (!isNaN(pid) && pid > 0) {
            pids.add(pid);
          }
        }
      });
    } catch {
      // No processes found or error - that's okay
    }
  } else {
    // Linux
    try {
      const { stdout } = await execAsync(`pgrep -f cursor`);
      const pidLines = stdout.trim().split('\n').filter(line => line.trim());
      pidLines.forEach(line => {
        const pid = parseInt(line.trim(), 10);
        if (!isNaN(pid) && pid > 0) {
          pids.add(pid);
        }
      });
    } catch {
      // No processes found or error - that's okay
    }
  }
  
  return pids;
}

/**
 * Helper function to verify a PID is still running
 */
async function isPidRunning(pid: number): Promise<boolean> {
  if (process.platform === 'darwin' || process.platform === 'linux') {
    try {
      await execAsync(`ps -p ${pid} -o pid=`);
      return true;
    } catch {
      return false;
    }
  } else {
    // Windows
    try {
      const { stdout } = await execAsync(`tasklist /FI "PID eq ${pid}" /FO CSV | findstr ${pid}`);
      return !!stdout;
    } catch {
      return false;
    }
  }
}

describe('RemoteController startCursor Interruption Detection', () => {
  let component: DefaultRemoteController;
  let initialCursorPids: Set<number>;
  
  beforeAll(async () => {
    component = new DefaultRemoteController();
    await component.init({});
    
    // Get initial Cursor PIDs before any test runs
    initialCursorPids = await getCursorPids();
  });
  
  it('should NOT interrupt or kill existing Cursor instances when startCursor is called', async () => {
    // Skip test if Cursor is not installed or not available on this platform
    if (process.platform === 'darwin') {
      const cursorPath = '/Applications/Cursor.app';
      if (!existsSync(cursorPath)) {
        console.log('   ⏭️  Skipping test: Cursor.app not found at /Applications/Cursor.app');
        return;
      }
    }
    
    // Get Cursor PIDs BEFORE calling startCursor
    const pidsBefore = await getCursorPids();
    console.log(`   📋 Cursor PIDs before startCursor: ${Array.from(pidsBefore).join(', ') || 'none'}`);
    
    // Call startCursor
    try {
      await component.startCursor();
      
      // Wait a bit for any process changes to settle
      await new Promise(resolve => setTimeout(resolve, 3000));
      
      // Get Cursor PIDs AFTER calling startCursor
      const pidsAfter = await getCursorPids();
      console.log(`   📋 Cursor PIDs after startCursor: ${Array.from(pidsAfter).join(', ') || 'none'}`);
      
      // CRITICAL TEST: All PIDs that existed before should still exist after
      const interruptedPids: number[] = [];
      for (const pid of pidsBefore) {
        const stillRunning = await isPidRunning(pid);
        if (!stillRunning) {
          interruptedPids.push(pid);
        }
      }
      
      if (interruptedPids.length > 0) {
        console.error(`   ❌ INTERRUPTION DETECTED: The following Cursor PIDs were killed:`);
        console.error(`      ${interruptedPids.join(', ')}`);
        console.error(`   🔴 BUG: startCursor() killed existing Cursor instances!`);
        throw new Error(`startCursor() interrupted ${interruptedPids.length} existing Cursor instance(s): ${interruptedPids.join(', ')}`);
      }
      
      // Additional check: Verify that at least the same number of processes exist
      // (or more, if a new instance was created)
      if (pidsAfter.size < pidsBefore.size) {
        const lostPids = Array.from(pidsBefore).filter(pid => !pidsAfter.has(pid));
        console.error(`   ❌ INTERRUPTION DETECTED: Lost ${lostPids.length} Cursor process(es): ${lostPids.join(', ')}`);
        throw new Error(`startCursor() caused ${lostPids.length} Cursor process(es) to disappear: ${lostPids.join(', ')}`);
      }
      
      console.log(`   ✅ No interruption detected: All ${pidsBefore.size} existing Cursor instance(s) remain running`);
      
    } catch (error: any) {
      // If the error is our interruption detection, re-throw it
      if (error.message && (error.message.includes('INTERRUPTION DETECTED') || error.message.includes('interrupted'))) {
        throw error;
      }
      
      // For other errors (like Cursor not starting), log but don't fail the test
      // The test is specifically about NOT interrupting existing instances
      console.log(`   ⚠️  startCursor() encountered an error: ${error.message}`);
      console.log(`   ℹ️  This is acceptable - the test is about NOT interrupting existing instances`);
      
      // Still verify that existing PIDs weren't killed
      const stillRunningPids: number[] = [];
      const killedPids: number[] = [];
      
      for (const pid of pidsBefore) {
        const stillRunning = await isPidRunning(pid);
        if (stillRunning) {
          stillRunningPids.push(pid);
        } else {
          killedPids.push(pid);
        }
      }
      
      if (killedPids.length > 0) {
        console.error(`   ❌ INTERRUPTION DETECTED: The following Cursor PIDs were killed despite error:`);
        console.error(`      ${killedPids.join(', ')}`);
        throw new Error(`startCursor() killed ${killedPids.length} existing Cursor instance(s) even when it encountered an error: ${killedPids.join(', ')}`);
      }
      
      console.log(`   ✅ No interruption detected: All ${pidsBefore.size} existing Cursor instance(s) remain running despite error`);
    }
  }, 60000); // 60 second timeout for this test
  
  afterAll(async () => {
    // Clean up: Don't leave any tracked PIDs from the test
    // This ensures the test doesn't interfere with subsequent tests
    try {
      const fs = await import('fs/promises');
      const os = await import('os');
      const pidFile = path.join(os.tmpdir(), 'remotecontroller-cursor.pid');
      if (existsSync(pidFile)) {
        await fs.unlink(pidFile);
        console.log('   🧹 Cleaned up test PID file');
      }
    } catch {
      // Ignore cleanup errors
    }
  });
});

