#!/bin/bash
# Simple Memory Generation Script for Web4Articles
# Version: 1.0 (Simplified)
# Purpose: Generate comprehensive memory.md from project markdown files

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
WORKSPACE_ROOT="$(git rev-parse --show-toplevel)"
MEMORY_FILE="$WORKSPACE_ROOT/memory.md"

echo -e "${BLUE}🧠 Simple Memory Generation Script v1.0${NC}"
echo -e "${BLUE}===========================================${NC}"

cd "$WORKSPACE_ROOT"
START_TIME=$(date +%s)

# Core files to always include
CORE_FILES=(
    "README.md"
    "index.md"
    "scrum.pmo/roles/_shared/PDCA/howto.PDCA.md"
    "scrum.pmo/roles/_shared/PDCA/template.md"
    "scrum.pmo/roles/_shared/PDCA/PDCA.howto.decide.md"
)

# Find additional files
echo -e "${YELLOW}📋 Discovering files...${NC}"

ALL_FILES=()
# Add core files
for file in "${CORE_FILES[@]}"; do
    if [[ -f "$file" ]]; then
        ALL_FILES+=("$file")
        echo "  ✅ Core: $file"
    fi
done

# Add role process files
while IFS= read -r -d '' file; do
    rel_file="${file#$WORKSPACE_ROOT/}"
    ALL_FILES+=("$rel_file")
    echo "  ✅ Role: $rel_file"
done < <(find "scrum.pmo/roles" -name "process.md" -print0 2>/dev/null)

# Add documentation files
while IFS= read -r -d '' file; do
    rel_file="${file#$WORKSPACE_ROOT/}"
    ALL_FILES+=("$rel_file")
    echo "  ✅ Doc: $rel_file"
done < <(find "docs" -name "*.md" -print0 2>/dev/null)

# Add other important files
for file in "recovery.md" "docs/tech-stack.md"; do
    if [[ -f "$file" ]]; then
        ALL_FILES+=("$file")
        echo "  ✅ Extra: $file"
    fi
done

echo "  📊 Total files: ${#ALL_FILES[@]}"

# Generate memory.md
echo -e "${YELLOW}📋 Generating memory.md...${NC}"

cat > "$MEMORY_FILE" << EOF
# Agent Context Memory
**Last Updated:** $(date -u +"%Y-%m-%d-UTC-%H%M")
**Version:** 1.0
**Generated By:** Simple Memory Generation Script
**Files Crawled:** ${#ALL_FILES[@]} markdown files
**Deduplication Applied:** KISS + DRY rules

---

## Project Overview

**Web4Articles** is a DAPP (Decentralized Application) for collective intelligence in article writing. The project implements a comprehensive Web4 methodology with structured development processes, PDCA (Plan-Do-Check-Act) cycles, and multi-agent coordination.

### Core Philosophy
- **"Never 2 1 (TO ONE). Always 4 2 (FOR TWO)."** - Collaborative intelligence principle
- **CMMI Level 4** process compliance with systematic improvement
- **DRY (Don't Repeat Yourself)** - No duplication of logic, documentation, or code
- **KISS (Keep It Simple, Stupid)** - Simple, clear solutions over complexity

---

## Process Framework

### PDCA System (Plan-Do-Check-Act)
**Template Version:** 3.1.4.2
**Location:** \`scrum.pmo/roles/_shared/PDCA/template.md\`

#### Mandatory 6-Section Format:
1. **Strict Header** - UTC timestamp, agent info, branch, sync requirements
2. **Summary with Dual Links** - GitHub | local paths, QA decisions, TRON feedback
3. **Horizontal Separators** - Between all sections
4. **QA Feedback in Check** - Verbatim quotes with UTC timestamps
5. **Emotional Reflection** - Personal growth and journey aspects
6. **PDCA Process Update** - Learning and quality impact

#### Critical Requirements:
- **Dual Link Format:** \`[GitHub](URL) | [local/path](path)\`
- **Verbatim TRON Quotes:** Never paraphrase user feedback
- **UTC Timestamps:** All dates in YYYY-MM-DD-UTC-HHMM format
- **Immediate Commit & Push:** After every PDCA creation

### Agent Roles & Responsibilities

EOF

# Add role information
echo "" >> "$MEMORY_FILE"
for file in "${ALL_FILES[@]}"; do
    if [[ "$file" == scrum.pmo/roles/*/process.md ]]; then
        role_name=$(basename "$(dirname "$file")")
        echo "#### $role_name" >> "$MEMORY_FILE"
        
        # Extract purpose if available
        if grep -q "Purpose:" "$file" 2>/dev/null; then
            purpose=$(grep "Purpose:" "$file" | head -1 | sed 's/.*Purpose: *//' | sed 's/\*\*//g')
            echo "- **Purpose:** $purpose" >> "$MEMORY_FILE"
        elif grep -q "Role Definition" "$file" 2>/dev/null; then
            # Get text after "Role Definition"
            definition=$(grep -A 3 "Role Definition" "$file" | tail -2 | tr '\n' ' ' | sed 's/- //g' | sed 's/\*\*//g')
            echo "- **Purpose:** $definition" >> "$MEMORY_FILE"
        fi
        
        echo "- **Process:** $file" >> "$MEMORY_FILE"
        echo "" >> "$MEMORY_FILE"
    fi
done

# Continue with rest of template
cat >> "$MEMORY_FILE" << 'EOF'

---

## Current State

### Active Sprint Information
**Current Branch:** CURRENT_BRANCH_PLACEHOLDER
**Latest Commit:** LATEST_COMMIT_PLACEHOLDER

### Project Structure
```
Web4Articles/
├── components/          # Web4 components (TSRanger, Unit, etc.)
├── scrum.pmo/          # Project management office
│   ├── roles/          # Agent role definitions
│   ├── sprints/        # Sprint planning and tasks
│   └── project.journal/ # Session documentation
├── docs/               # Technical documentation
├── scripts/            # Automation and utilities
└── spec/               # Requirements and specifications
```

---

## Technical Context

### Technology Stack
- **Testing:** Vitest (Jest banned), ESM-native, TypeScript-first
- **Architecture:** 5-layer component structure, strict OOP
- **Tools:** Docker, PlantUML, Graphviz, GitHub CLI
- **Patterns:** Web4 constructor pattern, scenario hibernation, IOR references

### Web4 Methodology
- **Empty Constructors:** All objects use `constructor() {}`
- **Scenario Initialization:** Objects initialize from serialized scenarios
- **IOR System:** Internet Object Reference for distributed objects
- **Hibernation:** Complete object state serialization/restoration

---

## Decision Framework

### QA Decision Format
```markdown
### **QA Decisions**
- [x] Completed decision: [Description]
- [ ] **Decision 1:** [Clear title]
  - a) [Option with rationale]
  - b) [Option with rationale]
```

### When to Present Decisions
- **Real Risk Exists:** Destructive operations, data loss potential
- **Multiple Valid Approaches:** Different implementation strategies
- **Ambiguous Requirements:** Unclear user instructions
- **Significant Impact:** Architecture, long-term maintenance

---

## Key Files & Links

### Core Process Files
EOF

# Add core files list
for file in "${CORE_FILES[@]}"; do
    if [[ -f "$file" ]]; then
        echo "- **$(basename "$file")** - $file" >> "$MEMORY_FILE"
    fi
done

echo "" >> "$MEMORY_FILE"
echo "### Role Process Files" >> "$MEMORY_FILE"

# Add role files list
for file in "${ALL_FILES[@]}"; do
    if [[ "$file" == scrum.pmo/roles/*/process.md ]]; then
        role_name=$(basename "$(dirname "$file")")
        echo "- **$role_name** - $file" >> "$MEMORY_FILE"
    fi
done

# Finish the template
cat >> "$MEMORY_FILE" << 'EOF'

---

## Agent Startup Process

### Identity First Protocol
1. **Run Identity Check:** `./scripts/agent-identity-first-startup.sh`
2. **Verify RequestID:** Check Cursor UI or environment variable
3. **Read Identity Record:** `scrum.pmo/agents/registry/[REQUEST-ID].md`
4. **Follow Role Process:** Read appropriate process.md file

### Session Initialization
1. **Create Session Directory:** `scrum.pmo/project.journal/$(date -u +"%Y-%m-%d-UTC-%H%M")-session`
2. **Create Project Status:** Document current state
3. **Create Dev Branch:** `dev/$(date -u +"%Y-%m-%d-UTC-%H%M")`
4. **Create Session Start PDCA:** Document intentions and decisions

---

## Quality Standards

### Code Quality
- **Testing:** Vitest only, comprehensive coverage, non-interactive tests
- **Architecture:** 5-layer structure, strict OOP, DRY principles
- **Documentation:** Dual links, verbatim quotes, UTC timestamps
- **Process:** PDCA for all significant work, immediate commit/push

### Process Compliance
- **CMMI Level 4:** Systematic process improvement
- **Traceability:** Complete artifact linking and version control
- **Collaboration:** Multi-agent coordination with role switching
- **Learning:** Continuous improvement through PDCA cycles

---

## Communication Protocol

### Chat Responses
- **Detailed content in PDCAs** - NOT in chat
- **Dual links and decisions ONLY** in chat
- **Copy QA decisions EXACTLY** from PDCA to chat
- **Never create different decisions** in chat vs PDCA

---

## Quick Reference Commands

### Identity & Startup
```bash
# Start every session
./scripts/agent-identity-first-startup.sh

# Check current branch
git branch --show-current

# Generate/update memory
./scripts/generate-memory.sh
```

### PDCA Creation
```bash
# Use template from
scrum.pmo/roles/_shared/PDCA/template.md

# Commit and push immediately
git add -A
git commit -m "PDCA: [Title from PDCA header]"
git push origin [branch]
```

---

**🎯 This memory.md provides comprehensive context for all agent operations, ensuring consistent understanding and process compliance across all roles and sessions.**

**"Never 2 1 (TO ONE). Always 4 2 (FOR TWO)."** 🤝✨
EOF

# Replace placeholders with actual values using Python (more reliable than sed)
current_branch=$(git branch --show-current 2>/dev/null || echo "Unknown")
latest_commit=$(git log -1 --pretty=format:"%h - %s" 2>/dev/null || echo "Unknown")

python3 -c "
import re
with open('$MEMORY_FILE', 'r') as f:
    content = f.read()
content = content.replace('CURRENT_BRANCH_PLACEHOLDER', '$current_branch')
content = content.replace('LATEST_COMMIT_PLACEHOLDER', '''$latest_commit''')
with open('$MEMORY_FILE', 'w') as f:
    f.write(content)
"

# Calculate generation time
END_TIME=$(date +%s)
GENERATION_TIME=$((END_TIME - START_TIME))

echo -e "${GREEN}✅ Memory generation completed!${NC}"
echo -e "${GREEN}📊 Statistics:${NC}"
echo "  📁 Files processed: ${#ALL_FILES[@]}"
echo "  ⏱️  Generation time: ${GENERATION_TIME}s"
echo "  📄 Output file: $MEMORY_FILE"

# Check file size and estimate tokens
if [[ -f "$MEMORY_FILE" ]]; then
    size=$(wc -c < "$MEMORY_FILE")
    words=$(wc -w < "$MEMORY_FILE")
    estimated_tokens=$((words * 140 / 100))
    
    echo "  📏 File size: $size bytes"
    echo "  📝 Words: $words"
    echo "  🎯 Estimated tokens: $estimated_tokens"
    
    if [[ $estimated_tokens -gt 5000 ]]; then
        echo -e "${YELLOW}⚠️  Warning: Estimated tokens ($estimated_tokens) exceed 5,000 target${NC}"
    else
        echo -e "${GREEN}✅ Token count within target (<5,000)${NC}"
    fi
fi

echo -e "${BLUE}🎯 Simple memory generation completed successfully!${NC}"
