#!/bin/bash
# setup-once-links.sh - Build process integration for ONCE demo links

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS_DIR="$PROJECT_ROOT/scripts"
VERSIONS_DIR="$SCRIPTS_DIR/versions"
ONCE_VERSION="0.1.0.0"

echo "🔧 Setting up ONCE demo links..."

# Create directories if they don't exist
mkdir -p "$VERSIONS_DIR"

# Create versioned ONCE script
ONCE_VERSIONED="$VERSIONS_DIR/once$ONCE_VERSION"
cat > "$ONCE_VERSIONED" << 'EOF'
#!/bin/bash
# ONCE Interactive Demo v0.1.0.0 - Location Resilient Launcher
# Generated by setup-once-links.sh

find_project_root() {
    local current_dir="$PWD"
    local git_root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ -n "$git_root" ]; then
        echo "$git_root"
        return 0
    fi
    
    local dir="$current_dir"
    while [ "$dir" != "/" ]; do
        if [ -f "$dir/package.json" ]; then
            echo "$dir"
            return 0
        fi
        dir=$(dirname "$dir")
    done
    
    echo "$current_dir"
}

PROJECT_ROOT=$(find_project_root)
ONCE_VERSION="0.1.0.0"
DEMO_PATH="$PROJECT_ROOT/components/ONCE/$ONCE_VERSION/examples/multi-env-demo"
DEMO_SCRIPT="$DEMO_PATH/interactive-demo.js"

if [ ! -f "$DEMO_SCRIPT" ]; then
    echo "❌ ONCE Demo not found at: $DEMO_SCRIPT"
    echo "📁 Expected path: components/ONCE/$ONCE_VERSION/examples/multi-env-demo/"
    exit 1
fi

CURRENT_DIR="$PWD"
cd "$DEMO_PATH"

# Handle command line arguments
if [ $# -eq 0 ]; then
    echo "🎭 Starting ONCE Interactive Demo v$ONCE_VERSION..."
    echo "📁 Demo path: $DEMO_PATH"
    echo "🌐 Browser auto-opening enabled"
    node interactive-demo.js
elif [ "$1" = "--headless" ]; then
    echo "🎭 Starting ONCE Demo v$ONCE_VERSION (headless mode)..."
    echo "📁 Demo path: $DEMO_PATH"
    echo "🖥️  Server-only mode (no browser auto-opening)"
    node interactive-demo.js --headless
elif [ "$1" = "--help" ] || [ "$1" = "help" ]; then
    echo ""
    echo "🎭 ONCE Interactive Demo v$ONCE_VERSION"
    echo "Web4 Universal P2P Communication Engine"
    echo ""
    echo "Usage:"
    echo "  once0.1.0.0                  # Start interactive demo with browser"
    echo "  once0.1.0.0 --headless       # Start demo without browser"
    echo "  once0.1.0.0 --help           # Show this help"
    echo ""
    echo "Demo Controls (interactive mode):"
    echo "  [s] Start/Stop ONCE server"
    echo "  [1] Launch Browser Client"
    echo "  [2] Launch Node.js Client" 
    echo "  [3] Launch Web Worker Client"
    echo "  [d] Discover peers"
    echo "  [e] Exchange scenarios"
    echo "  [q] Quit demo"
    echo ""
    echo "Features:"
    echo "  • Cross-platform browser auto-opening"
    echo "  • Web4 Message component integration"
    echo "  • P2P scenario acknowledgments"
    echo "  • Interactive demo controls"
    echo ""
    cd "$CURRENT_DIR"
    exit 0
else
    echo "🎭 Starting ONCE Interactive Demo v$ONCE_VERSION..."
    echo "📁 Demo path: $DEMO_PATH"
    echo "🌐 Browser auto-opening enabled"
    node interactive-demo.js "$@"
fi

cd "$CURRENT_DIR"
EOF

# Make versioned script executable
chmod +x "$ONCE_VERSIONED"

# Create latest ONCE script
ONCE_LATEST="$SCRIPTS_DIR/once"
cat > "$ONCE_LATEST" << 'EOF'
#!/bin/bash
# ONCE Interactive Demo - Latest Version Launcher
# Generated by setup-once-links.sh

find_project_root() {
    local current_dir="$PWD"
    local git_root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ -n "$git_root" ]; then
        echo "$git_root"
        return 0
    fi
    
    local dir="$current_dir"
    while [ "$dir" != "/" ]; do
        if [ -f "$dir/package.json" ]; then
            echo "$dir"
            return 0
        fi
        dir=$(dirname "$dir")
    done
    
    echo "$current_dir"
}

PROJECT_ROOT=$(find_project_root)
LATEST_VERSION="0.1.0.0"
VERSIONED_SCRIPT="$PROJECT_ROOT/scripts/versions/once$LATEST_VERSION"

if [ ! -f "$VERSIONED_SCRIPT" ]; then
    echo "❌ Latest ONCE script not found: $VERSIONED_SCRIPT"
    echo "🔧 Run scripts/setup-once-links.sh to create ONCE links"
    exit 1
fi

# Show usage if no parameters provided
if [ $# -eq 0 ]; then
    echo ""
    echo "🎭 ONCE Interactive Demo - Web4 Universal P2P Communication Engine"
    echo ""
    echo "Usage:"
    echo "  once demo                    # Start interactive demo with browser auto-opening"
    echo "  once demo --headless         # Start demo without browser (server only)"
    echo "  once demo --help             # Show demo-specific help"
    echo "  once help                    # Show this help message"
    echo "  once version                 # Show ONCE version information"
    echo ""
    echo "Demo Features:"
    echo "  • Cross-platform browser auto-opening"
    echo "  • Web4 Message component integration"
    echo "  • P2P scenario acknowledgments"
    echo "  • Interactive demo controls"
    echo "  • TTY-aware keyboard input"
    echo ""
    echo "Examples:"
    echo "  once demo                    # Launch full interactive demo"
    echo "  once demo --headless         # Server-only mode for testing"
    echo ""
    echo "Location: Latest version (v$LATEST_VERSION)"
    echo "Path: scripts/versions/once$LATEST_VERSION"
    exit 0
fi

# Handle specific commands
case "$1" in
    "help"|"--help"|"-h")
        echo ""
        echo "🎭 ONCE Interactive Demo - Web4 Universal P2P Communication Engine"
        echo ""
        echo "Usage:"
        echo "  once demo                    # Start interactive demo"
        echo "  once demo --headless         # Start demo without browser"
        echo "  once demo --help             # Show demo help"
        echo "  once help                    # Show this help"
        echo "  once version                 # Show version info"
        echo ""
        exit 0
        ;;
    "version"|"--version"|"-v")
        echo "ONCE Interactive Demo v$LATEST_VERSION"
        echo "Web4 Universal P2P Communication Engine"
        echo "Path: $VERSIONED_SCRIPT"
        exit 0
        ;;
    "demo")
        echo "🚀 Launching ONCE Demo (latest: v$LATEST_VERSION)..."
        shift  # Remove 'demo' from arguments
        exec "$VERSIONED_SCRIPT" "$@"
        ;;
    *)
        echo "❌ Unknown command: $1"
        echo "Run 'once help' for usage information"
        exit 1
        ;;
esac
EOF

# Make latest script executable
chmod +x "$ONCE_LATEST"

echo "✅ ONCE demo links created:"
echo "   📁 Versioned: $ONCE_VERSIONED"
echo "   📁 Latest: $ONCE_LATEST"
echo ""
echo "🎭 Usage:"
echo "   scripts/versions/once$ONCE_VERSION    # Specific version"
echo "   scripts/once                          # Latest version"
echo ""
echo "🌐 Demo features:"
echo "   • Cross-platform browser auto-opening"
echo "   • Web4 Message component integration"
echo "   • P2P scenario acknowledgments"
echo "   • Interactive demo controls"
