#!/bin/bash
# setup-once-links.sh - Build process integration for ONCE demo links

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS_DIR="$PROJECT_ROOT/scripts"
VERSIONS_DIR="$SCRIPTS_DIR/versions"
ONCE_VERSION="0.1.0.0"

echo "🔧 Setting up ONCE demo links..."

# Create directories if they don't exist
mkdir -p "$VERSIONS_DIR"

# Create versioned ONCE script
ONCE_VERSIONED="$VERSIONS_DIR/once$ONCE_VERSION"
cat > "$ONCE_VERSIONED" << 'EOF'
#!/bin/bash
# ONCE Interactive Demo v0.1.0.0 - Location Resilient Launcher
# Generated by setup-once-links.sh

find_project_root() {
    local current_dir="$PWD"
    local git_root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ -n "$git_root" ]; then
        echo "$git_root"
        return 0
    fi
    
    local dir="$current_dir"
    while [ "$dir" != "/" ]; do
        if [ -f "$dir/package.json" ]; then
            echo "$dir"
            return 0
        fi
        dir=$(dirname "$dir")
    done
    
    echo "$current_dir"
}

PROJECT_ROOT=$(find_project_root)
ONCE_VERSION="0.1.0.0"
DEMO_PATH="$PROJECT_ROOT/components/ONCE/$ONCE_VERSION/examples/multi-env-demo"
DEMO_SCRIPT="$DEMO_PATH/interactive-demo.js"

if [ ! -f "$DEMO_SCRIPT" ]; then
    echo "❌ ONCE Demo not found at: $DEMO_SCRIPT"
    echo "📁 Expected path: components/ONCE/$ONCE_VERSION/examples/multi-env-demo/"
    exit 1
fi

# Color codes following Web4 CLI color standards
CYAN='\x1b[36m'
YELLOW='\x1b[33m'
BLUE='\x1b[34m'
MAGENTA='\x1b[35m'
BOLD='\x1b[1m'
RESET='\x1b[0m'

CURRENT_DIR="$PWD"
cd "$DEMO_PATH"

# Handle command line arguments
if [ $# -eq 0 ]; then
    echo -e "${CYAN}🎭 Starting ONCE Interactive Demo ${YELLOW}v$ONCE_VERSION${RESET}${CYAN}...${RESET}"
    echo -e "${BOLD}📁 Demo path:${RESET} ${YELLOW}$DEMO_PATH${RESET}"
    echo -e "${CYAN}🌐 Browser auto-opening enabled${RESET}"
    node interactive-demo.js
elif [ "$1" = "--headless" ]; then
    echo -e "${CYAN}🎭 Starting ONCE Demo ${YELLOW}v$ONCE_VERSION${RESET} ${MAGENTA}(headless mode)${RESET}${CYAN}...${RESET}"
    echo -e "${BOLD}📁 Demo path:${RESET} ${YELLOW}$DEMO_PATH${RESET}"
    echo -e "${MAGENTA}🖥️  Server-only mode (no browser auto-opening)${RESET}"
    node interactive-demo.js --headless
elif [ "$1" = "--help" ] || [ "$1" = "help" ]; then
    echo ""
    echo -e "${CYAN}${BOLD}🎭 ONCE Interactive Demo${RESET} ${YELLOW}v$ONCE_VERSION${RESET}"
    echo -e "${BOLD}Web4 Universal P2P Communication Engine${RESET}"
    echo ""
    echo -e "${BOLD}Usage:${RESET}"
    echo -e "  ${CYAN}once0.1.0.0${RESET}                  # Start interactive demo with browser"
    echo -e "  ${CYAN}once0.1.0.0 --headless${RESET}       # Start demo without browser"
    echo -e "  ${CYAN}once0.1.0.0 --help${RESET}           # Show this help"
    echo ""
    echo -e "${BOLD}Demo Controls (interactive mode):${RESET}"
    echo -e "  ${YELLOW}[s]${RESET} Start/Stop ONCE server"
    echo -e "  ${YELLOW}[1]${RESET} Launch Browser Client"
    echo -e "  ${YELLOW}[2]${RESET} Launch Node.js Client" 
    echo -e "  ${YELLOW}[3]${RESET} Launch Web Worker Client"
    echo -e "  ${YELLOW}[d]${RESET} Discover peers"
    echo -e "  ${YELLOW}[e]${RESET} Exchange scenarios"
    echo -e "  ${YELLOW}[q]${RESET} Quit demo"
    echo ""
    echo -e "${BOLD}Features:${RESET}"
    echo -e "  ${BLUE}•${RESET} Cross-platform browser auto-opening"
    echo -e "  ${BLUE}•${RESET} Web4 Message component integration"
    echo -e "  ${BLUE}•${RESET} P2P scenario acknowledgments"
    echo -e "  ${BLUE}•${RESET} Interactive demo controls"
    echo ""
    cd "$CURRENT_DIR"
    exit 0
else
    echo -e "${CYAN}🎭 Starting ONCE Interactive Demo ${YELLOW}v$ONCE_VERSION${RESET}${CYAN}...${RESET}"
    echo -e "${BOLD}📁 Demo path:${RESET} ${YELLOW}$DEMO_PATH${RESET}"
    echo -e "${CYAN}🌐 Browser auto-opening enabled${RESET}"
    node interactive-demo.js "$@"
fi

cd "$CURRENT_DIR"
EOF

# Make versioned script executable
chmod +x "$ONCE_VERSIONED"

# Create latest ONCE script
ONCE_LATEST="$SCRIPTS_DIR/once"
cat > "$ONCE_LATEST" << 'EOF'
#!/bin/bash
# ONCE Interactive Demo - Latest Version Launcher
# Generated by setup-once-links.sh

find_project_root() {
    local current_dir="$PWD"
    local git_root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ -n "$git_root" ]; then
        echo "$git_root"
        return 0
    fi
    
    local dir="$current_dir"
    while [ "$dir" != "/" ]; do
        if [ -f "$dir/package.json" ]; then
            echo "$dir"
            return 0
        fi
        dir=$(dirname "$dir")
    done
    
    echo "$current_dir"
}

PROJECT_ROOT=$(find_project_root)
LATEST_VERSION="0.1.0.0"
VERSIONED_SCRIPT="$PROJECT_ROOT/scripts/versions/once$LATEST_VERSION"

if [ ! -f "$VERSIONED_SCRIPT" ]; then
    echo "❌ Latest ONCE script not found: $VERSIONED_SCRIPT"
    echo "🔧 Run scripts/setup-once-links.sh to create ONCE links"
    exit 1
fi

# Color codes following Web4 CLI color standards
CYAN='\x1b[36m'
YELLOW='\x1b[33m'
BLUE='\x1b[34m'
BOLD='\x1b[1m'
RESET='\x1b[0m'

# Show usage if no parameters provided
if [ $# -eq 0 ]; then
    echo ""
    echo -e "${CYAN}${BOLD}🎭 ONCE Interactive Demo${RESET} - Web4 Universal P2P Communication Engine"
    echo ""
    echo -e "${BOLD}Usage:${RESET}"
    echo -e "  ${CYAN}once demo${RESET}                    # Start interactive demo with browser auto-opening"
    echo -e "  ${CYAN}once demo --headless${RESET}         # Start demo without browser (server only)"
    echo -e "  ${CYAN}once demo --help${RESET}             # Show demo-specific help"
    echo -e "  ${CYAN}once help${RESET}                    # Show this help message"
    echo -e "  ${CYAN}once version${RESET}                 # Show ONCE version information"
    echo ""
    echo -e "${BOLD}Demo Features:${RESET}"
    echo -e "  ${BLUE}•${RESET} Cross-platform browser auto-opening"
    echo -e "  ${BLUE}•${RESET} Web4 Message component integration"
    echo -e "  ${BLUE}•${RESET} P2P scenario acknowledgments"
    echo -e "  ${BLUE}•${RESET} Interactive demo controls"
    echo -e "  ${BLUE}•${RESET} TTY-aware keyboard input"
    echo ""
    echo -e "${BOLD}Examples:${RESET}"
    echo -e "  ${CYAN}once demo${RESET}                    # Launch full interactive demo"
    echo -e "  ${CYAN}once demo --headless${RESET}         # Server-only mode for testing"
    echo ""
    echo -e "${BOLD}Location:${RESET} Latest version (${YELLOW}v$LATEST_VERSION${RESET})"
    echo -e "${BOLD}Path:${RESET} ${YELLOW}scripts/versions/once$LATEST_VERSION${RESET}"
    exit 0
fi

# Handle specific commands
case "$1" in
    "help"|"--help"|"-h")
        echo ""
        echo -e "${CYAN}${BOLD}🎭 ONCE Interactive Demo${RESET} - Web4 Universal P2P Communication Engine"
        echo ""
        echo -e "${BOLD}Usage:${RESET}"
        echo -e "  ${CYAN}once demo${RESET}                    # Start interactive demo"
        echo -e "  ${CYAN}once demo --headless${RESET}         # Start demo without browser"
        echo -e "  ${CYAN}once demo --help${RESET}             # Show demo help"
        echo -e "  ${CYAN}once help${RESET}                    # Show this help"
        echo -e "  ${CYAN}once version${RESET}                 # Show version info"
        echo ""
        exit 0
        ;;
    "version"|"--version"|"-v")
        echo -e "${BOLD}ONCE Interactive Demo${RESET} ${YELLOW}v$LATEST_VERSION${RESET}"
        echo -e "${BOLD}Web4 Universal P2P Communication Engine${RESET}"
        echo -e "${BOLD}Path:${RESET} ${YELLOW}$VERSIONED_SCRIPT${RESET}"
        exit 0
        ;;
    "demo")
        echo -e "${CYAN}🚀 Launching ONCE Demo (latest: ${YELLOW}v$LATEST_VERSION${RESET}${CYAN})...${RESET}"
        shift  # Remove 'demo' from arguments
        exec "$VERSIONED_SCRIPT" "$@"
        ;;
    *)
        echo -e "${BOLD}❌ Unknown command:${RESET} ${YELLOW}$1${RESET}"
        echo -e "Run '${CYAN}once help${RESET}' for usage information"
        exit 1
        ;;
esac
EOF

# Make latest script executable
chmod +x "$ONCE_LATEST"

echo "✅ ONCE demo links created:"
echo "   📁 Versioned: $ONCE_VERSIONED"
echo "   📁 Latest: $ONCE_LATEST"
echo ""
echo "🎭 Usage:"
echo "   scripts/versions/once$ONCE_VERSION    # Specific version"
echo "   scripts/once                          # Latest version"
echo ""
echo "🌐 Demo features:"
echo "   • Cross-platform browser auto-opening"
echo "   • Web4 Message component integration"
echo "   • P2P scenario acknowledgments"
echo "   • Interactive demo controls"
