#!/bin/bash
# setup-once-links.sh - Build process integration for ONCE demo links

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS_DIR="$PROJECT_ROOT/scripts"
VERSIONS_DIR="$SCRIPTS_DIR/versions"
ONCE_VERSION="0.1.0.0"

echo "🔧 Setting up ONCE demo links..."

# Create directories if they don't exist
mkdir -p "$VERSIONS_DIR"

# Create versioned ONCE script
ONCE_VERSIONED="$VERSIONS_DIR/once$ONCE_VERSION"
cat > "$ONCE_VERSIONED" << 'EOF'
#!/bin/bash
# ONCE Interactive Demo v0.1.0.0 - Location Resilient Launcher
# Generated by setup-once-links.sh

find_project_root() {
    local current_dir="$PWD"
    local git_root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ -n "$git_root" ]; then
        echo "$git_root"
        return 0
    fi
    
    local dir="$current_dir"
    while [ "$dir" != "/" ]; do
        if [ -f "$dir/package.json" ]; then
            echo "$dir"
            return 0
        fi
        dir=$(dirname "$dir")
    done
    
    echo "$current_dir"
}

PROJECT_ROOT=$(find_project_root)
ONCE_VERSION="0.1.0.0"
DEMO_PATH="$PROJECT_ROOT/components/ONCE/$ONCE_VERSION/examples/multi-env-demo"
DEMO_SCRIPT="$DEMO_PATH/interactive-demo.js"

if [ ! -f "$DEMO_SCRIPT" ]; then
    echo "❌ ONCE Demo not found at: $DEMO_SCRIPT"
    echo "📁 Expected path: components/ONCE/$ONCE_VERSION/examples/multi-env-demo/"
    exit 1
fi

CURRENT_DIR="$PWD"
cd "$DEMO_PATH"

echo "🎭 Starting ONCE Interactive Demo v$ONCE_VERSION..."
echo "📁 Demo path: $DEMO_PATH"
echo "🌐 Browser auto-opening enabled"

node interactive-demo.js "$@"
cd "$CURRENT_DIR"
EOF

# Make versioned script executable
chmod +x "$ONCE_VERSIONED"

# Create latest ONCE script
ONCE_LATEST="$SCRIPTS_DIR/once"
cat > "$ONCE_LATEST" << 'EOF'
#!/bin/bash
# ONCE Interactive Demo - Latest Version Launcher
# Generated by setup-once-links.sh

find_project_root() {
    local current_dir="$PWD"
    local git_root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ -n "$git_root" ]; then
        echo "$git_root"
        return 0
    fi
    
    local dir="$current_dir"
    while [ "$dir" != "/" ]; do
        if [ -f "$dir/package.json" ]; then
            echo "$dir"
            return 0
        fi
        dir=$(dirname "$dir")
    done
    
    echo "$current_dir"
}

PROJECT_ROOT=$(find_project_root)
LATEST_VERSION="0.1.0.0"
VERSIONED_SCRIPT="$PROJECT_ROOT/scripts/versions/once$LATEST_VERSION"

if [ ! -f "$VERSIONED_SCRIPT" ]; then
    echo "❌ Latest ONCE script not found: $VERSIONED_SCRIPT"
    echo "🔧 Run scripts/setup-once-links.sh to create ONCE links"
    exit 1
fi

echo "🚀 Launching ONCE Demo (latest: v$LATEST_VERSION)..."
exec "$VERSIONED_SCRIPT" "$@"
EOF

# Make latest script executable
chmod +x "$ONCE_LATEST"

echo "✅ ONCE demo links created:"
echo "   📁 Versioned: $ONCE_VERSIONED"
echo "   📁 Latest: $ONCE_LATEST"
echo ""
echo "🎭 Usage:"
echo "   scripts/versions/once$ONCE_VERSION    # Specific version"
echo "   scripts/once                          # Latest version"
echo ""
echo "🌐 Demo features:"
echo "   • Cross-platform browser auto-opening"
echo "   • Web4 Message component integration"
echo "   • P2P scenario acknowledgments"
echo "   • Interactive demo controls"
