/**
 * Generated Component Testing Workflow Tests
 * 
 * Validates that components generated by Web4TSComponent:
 * 1. Can run npm test without recursion
 * 2. Can delegate to web4tscomponent for promotion workflow
 * 3. Have proper recursion prevention (VITEST env check)
 * 4. test.sh runs vitest directly (no CLI delegation)
 * 5. CLI test() method delegates to web4tscomponent when not in vitest
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { DefaultWeb4TSComponent } from '../src/ts/layer2/DefaultWeb4TSComponent.js';
import { existsSync, rmSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

describe('🧪 Generated Component Testing Workflow', () => {
  let component: DefaultWeb4TSComponent;
  const testDataDir = path.join(__dirname, '..', 'test', 'data');
  const testComponentName = 'TestGeneratedComponent';
  
  beforeEach(() => {
    component = new DefaultWeb4TSComponent();
    component.setTargetDirectory(testDataDir);
  });

  afterEach(() => {
    // Clean up BEFORE next test (not after) to leave evidence visible
    // This will be called AFTER the current test completes
  });

  describe('📝 Story: Generated Component Test Infrastructure', () => {
    it('should create component with test.sh that calls component CLI test method', async () => {
      console.log('\n📖 Creating component and checking test.sh...');
      
      // Create component
      await component.create(testComponentName, '0.1.0.0', 'all');
      
      // Check test.sh content
      const testShPath = path.join(testDataDir, 'components', testComponentName, '0.1.0.0', 'src/sh/test.sh');
      expect(existsSync(testShPath)).toBe(true);
      
      const testShContent = readFileSync(testShPath, 'utf-8');
      
      // Verify it calls the component's CLI test method (which handles promotion)
      expect(testShContent).toContain('./testgeneratedcomponent test');
      expect(testShContent).not.toContain('npx vitest run');
      
      console.log('   ✅ test.sh calls component CLI test method');
      console.log('   ✅ Enables promotion workflow on 100% test success');
    });

    it('should create component with simple test() method that runs vitest', async () => {
      console.log('\n📖 Checking generated TypeScript test() method...');
      
      await component.create(testComponentName, '0.1.0.0', 'all');
      
      // Check DefaultTestGeneratedComponent.ts
      const componentImplPath = path.join(
        testDataDir, 
        'components', 
        testComponentName, 
        '0.1.0.0', 
        'src/ts/layer2',
        `Default${testComponentName}.ts`
      );
      expect(existsSync(componentImplPath)).toBe(true);
      
      const implContent = readFileSync(componentImplPath, 'utf-8');
      
      // Verify auto-promotion implementation (same as Web4TSComponent)
      expect(implContent).toContain('async test(): Promise<this>');
      expect(implContent).toContain('npx vitest run');
      expect(implContent).toContain('automatic promotion workflow');
      expect(implContent).toContain('Stage 0: prod (initial) → create dev');
      expect(implContent).toContain('Stage 1: dev → create test');
      expect(implContent).toContain('Stage 2: test + 100% → create prod + dev');
      
      // MUST have recursion detection
      expect(implContent).toContain('process.env.VITEST');
      expect(implContent).toContain('RECURSION DETECTION');
      
      // MUST use OOP (not shell exec to web4tscomponent)
      expect(implContent).toContain('DefaultWeb4TSComponent');
      expect(implContent).toContain('setTargetDirectory');
      expect(implContent).toContain('insideTestEnvironment');
      
      console.log('   ✅ test() method has auto-promotion logic');
      console.log('   ✅ Recursion prevention via VITEST env var');
      console.log('   ✅ Promotion via OOP (DefaultWeb4TSComponent instantiation)');
    });

    it('should allow npm test to run without recursion', async () => {
      console.log('\n📖 Testing npm test workflow (no recursion)...');
      
      await component.create(testComponentName, '0.1.0.0', 'all');
      
      const componentDir = path.join(testDataDir, 'components', testComponentName, '0.1.0.0');
      
      // Run npm test (should NOT recurse)
      // Note: First run includes installing 93 packages + building TypeScript
      // CRITICAL: Use clean environment (don't inherit VITEST from parent)
      const cleanEnv = { ...process.env };
      delete cleanEnv.VITEST;
      delete cleanEnv.VITEST_WORKER_ID;
      
      try {
        const result = execSync('npm test', {
          cwd: componentDir,
          encoding: 'utf-8',
          timeout: 120000, // 120 second timeout (first build is slow but should complete)
          env: cleanEnv // Use clean environment without VITEST
        });
        
        // If we get here, no infinite recursion occurred
        expect(result).toContain('Test Files');
        expect(result).toContain('passed');
        
        console.log('   ✅ npm test completed without recursion');
        console.log('   ✅ Tests ran successfully');
      } catch (error) {
        // If timeout, it means infinite recursion
        if ((error as any).killed) {
          throw new Error('npm test timed out - likely infinite recursion!');
        }
        throw error;
      }
    });

    it('should create component that documents promotion workflow in test() method', async () => {
      console.log('\n📖 Verifying promotion workflow documentation...');
      
      await component.create(testComponentName, '0.1.0.0', 'all');
      
      const componentImplPath = path.join(
        testDataDir, 
        'components', 
        testComponentName, 
        '0.1.0.0', 
        'src/ts/layer2',
        `Default${testComponentName}.ts`
      );
      
      const implContent = readFileSync(componentImplPath, 'utf-8');
      
      // Verify documentation about auto-promotion workflow
      expect(implContent).toContain('automatic promotion workflow');
      expect(implContent).toContain('Stage 0: prod (initial) → create dev');
      expect(implContent).toContain('Stage 1: dev → create test');
      expect(implContent).toContain('Stage 2: test + 100% → create prod + dev');
      expect(implContent).toContain('DefaultWeb4TSComponent'); // OOP instantiation
      
      console.log('   ✅ Component documents promotion workflow');
      console.log('   ✅ Auto-promotion via OOP (DefaultWeb4TSComponent)');
      console.log('   💡 Generated components promote themselves!');
    });

    it('should verify npm test works on generated component', async () => {
      console.log('\n📖 Verifying npm test works correctly...');
      
      await component.create(testComponentName, '0.1.0.0', 'all');
      
      const componentDir = path.join(testDataDir, 'components', testComponentName, '0.1.0.0');
      
      // Verify npm test works
      // CRITICAL: Use clean environment (don't inherit VITEST from parent)
      const cleanEnv = { ...process.env };
      delete cleanEnv.VITEST;
      delete cleanEnv.VITEST_WORKER_ID;
      
      const testResult = execSync('npm test', {
        cwd: componentDir,
        encoding: 'utf-8',
        timeout: 120000, // 120 second timeout (first build is slow)
        env: cleanEnv // Use clean environment without VITEST
      });
      expect(testResult).toContain('passed');
      
      console.log('   ✅ npm test runs with auto-promotion');
      console.log('   ✅ Recursion prevented via VITEST env var check');
      console.log('   💡 Generated components promote themselves!');
    });
  });

  describe('🔄 Web4TSComponent Promotion Workflow', () => {
    beforeEach(() => {
      // Clean up before each test in this describe block
      const componentDir = path.join(testDataDir, 'components', testComponentName);
      if (existsSync(componentDir)) {
        rmSync(componentDir, { recursive: true, force: true });
      }
    });

    it('should support correct promotion workflow stages', async () => {
      await component.create(testComponentName, '0.1.0.0', 'all');
      
      const componentDir = path.join(testDataDir, 'components', testComponentName);
      
      // Verify initial state: prod + latest only
      expect(existsSync(path.join(componentDir, 'prod'))).toBe(true);
      expect(existsSync(path.join(componentDir, 'latest'))).toBe(true);
      expect(existsSync(path.join(componentDir, 'dev'))).toBe(false);
      expect(existsSync(path.join(componentDir, 'test'))).toBe(false);
      
      console.log('   ✅ Initial: 0.1.0.0 → prod + latest (no dev/test yet)');
      console.log('   📋 Stage 0: First test run will create dev');
      console.log('   📋 Stage 1: Testing dev will create test');
      console.log('   📋 Stage 2: 100% test pass will promote to prod + create new dev');
    });


    it('should handle timeout gracefully if recursion occurs', async () => {
      // This test verifies our timeout mechanism works
      // If a component has infinite recursion, the test should fail with timeout
      // not hang forever
      
      await component.create(testComponentName, '0.1.0.0', 'all');
      
      const componentDir = path.join(testDataDir, 'components', testComponentName, '0.1.0.0');
      
      const startTime = Date.now();
      
      try {
        execSync('npm test', {
          cwd: componentDir,
          encoding: 'utf-8',
          timeout: 120000 // 120 second timeout (first run includes build)
        });
        
        const duration = Date.now() - startTime;
        
        // Test should complete without timeout (< 120 seconds)
        expect(duration).toBeLessThan(120000);
        
        console.log(`   ✅ Test completed in ${duration}ms (no recursion)`);
      } catch (error) {
        if ((error as any).killed) {
          throw new Error('Test killed by timeout - recursion detected!');
        }
        // Other errors are OK (test failures, etc.)
      }
    });

    // LAST TEST: Leave evidence visible for manual inspection
    it('should complete FULL promotion workflow: prod → dev → test → prod cycle (EVIDENCE LEFT VISIBLE)', async () => {
      console.log('\n📖 Testing COMPLETE promotion workflow...');
      console.log('⚠️  This test runs LAST to leave promotion evidence visible in test/data');
      
      // Stage 0: Create component
      console.log('\n🏗️  Stage 0: Create component...');
      await component.create(testComponentName, '0.1.0.0', 'all');
      
      let links = await component.getSemanticLinks(testComponentName);
      expect(links.prod).toBe('0.1.0.0');
      expect(links.dev).toBeNull();
      expect(links.test).toBeNull();
      console.log('   ✅ Created: 0.1.0.0 → prod + latest');
      
      // Stage 1: First test run → Create dev
      console.log('\n🚧 Stage 1: First test run → Create dev...');
      await component.on(testComponentName, '0.1.0.0');
      await component.test();
      
      links = await component.getSemanticLinks(testComponentName);
      expect(links.prod).toBe('0.1.0.0');
      expect(links.dev).toBe('0.1.0.1');
      expect(links.test).toBeNull();
      expect(existsSync(path.join(testDataDir, 'components', testComponentName, '0.1.0.1'))).toBe(true);
      console.log('   ✅ Stage 1: 0.1.0.0 (prod) → 0.1.0.1 (dev)');
      
      // Stage 2: Test dev → Create test
      console.log('\n🧪 Stage 2: Test dev → Create test...');
      await component.on(testComponentName, '0.1.0.1');
      await component.test();
      
      links = await component.getSemanticLinks(testComponentName);
      expect(links.prod).toBe('0.1.0.0');
      expect(links.dev).toBe('0.1.0.1');
      expect(links.test).toBe('0.1.0.2');
      expect(existsSync(path.join(testDataDir, 'components', testComponentName, '0.1.0.2'))).toBe(true);
      console.log('   ✅ Stage 2: 0.1.0.1 (dev) → 0.1.0.2 (test)');
      
      // Stage 3: Test with 100% → Promote to prod + create new dev
      console.log('\n🚀 Stage 3: Test with 100% → Promote to prod...');
      
      // CRITICAL: Create mock test-results.json with 100% success
      // (Vitest won't run due to recursion detection, so we mock the results)
      const testDir = path.join(testDataDir, 'components', testComponentName, '0.1.0.2', 'test');
      if (!existsSync(testDir)) {
        mkdirSync(testDir, { recursive: true });
      }
      const testResultsPath = path.join(testDir, 'test-results.json');
      const mockTestResults = {
        numTotalTests: 1,
        numFailedTests: 0,
        numPassedTests: 1,
        numPendingTests: 0,
        numTodoTests: 0,
        success: true
      };
      writeFileSync(testResultsPath, JSON.stringify(mockTestResults, null, 2));
      console.log('   ✅ Mock test results created (100% success)');
      
      await component.on(testComponentName, '0.1.0.2');
      await component.test();
      
      links = await component.getSemanticLinks(testComponentName);
      expect(links.prod).toBe('0.1.1.0');
      expect(links.dev).toBe('0.1.1.1');
      expect(links.test).toBe('0.1.1.1');
      expect(existsSync(path.join(testDataDir, 'components', testComponentName, '0.1.1.0'))).toBe(true);
      expect(existsSync(path.join(testDataDir, 'components', testComponentName, '0.1.1.1'))).toBe(true);
      console.log('   ✅ Stage 3: 0.1.0.2 (test) → 0.1.1.0 (prod) + 0.1.1.1 (dev)');
      
      console.log('\n🎉 COMPLETE WORKFLOW PROVEN:');
      console.log('   ✅ 0.1.0.0 → prod (initial)');
      console.log('   ✅ 0.1.0.1 → dev (Stage 1)');
      console.log('   ✅ 0.1.0.2 → test (Stage 2)');
      console.log('   ✅ 0.1.1.0 → prod (Stage 3)');
      console.log('   ✅ 0.1.1.1 → dev (Stage 3)');
      console.log('\n💡 Check evidence: test/data/components/TestGeneratedComponent/');
    });
  });

  describe('📝 Story: Generated Component CLI Location Resilience', () => {
    it('should create working CLI script symlinks that work from scripts/ directory', async () => {
      console.log('\n📖 Testing generated component CLI location resilience...');
      
      const componentName = 'TestCLIResilience';
      
      // Clean up if exists
      const componentPath = path.join(testDataDir, 'components', componentName);
      if (existsSync(componentPath)) {
        rmSync(componentPath, { recursive: true, force: true });
      }
      
      // Clean up scripts if exist
      const scriptsDir = path.join(testDataDir, 'scripts');
      const mainScriptPath = path.join(scriptsDir, componentName.toLowerCase());
      if (existsSync(mainScriptPath)) {
        rmSync(mainScriptPath, { force: true });
      }
      
      // Create component
      await component.create(componentName, '0.1.0.0', 'all');
      console.log('   ✅ Component created: TestCLIResilience 0.1.0.0');
      
      // Verify CLI script was created in component directory
      const componentCLIPath = path.join(componentPath, '0.1.0.0', 'testcliresilience');
      expect(existsSync(componentCLIPath)).toBe(true);
      console.log('   ✅ Component CLI script exists');
      
      // Verify main script symlink was created in scripts/
      expect(existsSync(mainScriptPath)).toBe(true);
      console.log('   ✅ Main script symlink exists in scripts/');
      
      // Test 1: Run CLI from component directory (should work)
      try {
        const result1 = execSync('./testcliresilience', {
          cwd: path.join(componentPath, '0.1.0.0'),
          encoding: 'utf-8'
        });
        expect(result1).toContain('TestCLIResilience CLI Tool');
        console.log('   ✅ CLI works from component directory');
      } catch (error) {
        console.error('   ❌ CLI failed from component directory');
        throw error;
      }
      
      // Test 2: Run CLI from scripts/ directory (THIS IS THE CRITICAL TEST)
      try {
        const result2 = execSync('./testcliresilience', {
          cwd: scriptsDir,
          encoding: 'utf-8',
          timeout: 10000
        });
        expect(result2).toContain('TestCLIResilience CLI Tool');
        console.log('   ✅ CLI works from scripts/ directory (location-resilient!)');
      } catch (error: any) {
        console.error('   ❌ CLI FAILED from scripts/ directory');
        console.error('   Error:', error.message);
        console.error('\n🔴 BUG FOUND: Generated CLI script is NOT location-resilient!');
        console.error('   This is the same bug that TestMyself revealed.');
        console.error('   The CLI script needs proper symlink resolution logic.');
        throw new Error(`CLI script is not location-resilient: ${error.message}`);
      }
      
      // Test 3: Run CLI from project root (should work)
      try {
        const result3 = execSync('./scripts/testcliresilience', {
          cwd: testDataDir,
          encoding: 'utf-8',
          timeout: 10000
        });
        expect(result3).toContain('TestCLIResilience CLI Tool');
        console.log('   ✅ CLI works from project root via scripts/');
      } catch (error) {
        console.error('   ❌ CLI failed from project root');
        throw error;
      }
      
      console.log('\n🎉 ALL LOCATION TESTS PASSED:');
      console.log('   ✅ From component directory');
      console.log('   ✅ From scripts/ directory');
      console.log('   ✅ From project root');
      console.log('\n💡 This test catches the TestMyself bug!');
    });
  });
});

