@startuml
title GitScrumProject CLI OOP Architecture


interface CLI {
  +start()
}

interface Project {
  +create(args: string[])
}

class DefaultCLI {
  +start()
}

class ParameterParser {
  -args: string[]
  +parse(): ParseArgs
}

class ParseArgs {
  +className
  +command
  +type
  +projectName
}

class GitScrumProject {
  -cli: CLI
  +static start()
  +create(args: string[])
  -createProject(projectName: string)
}

GitScrumProject o-- DefaultCLI : composes
DefaultCLI o-- ParameterParser : uses

CLI <|.. DefaultCLI
Project <|.. GitScrumProject

@enduml
